name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Build Docker image
    - name: Build Docker image
      run: docker build -t zeork7/test-lab1:latest .

    # Login to Docker Hub
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker push zeork7/test-lab1:latest

